sonar.projectKey=glideit
sonar.projectName=GlideIt
sonar.projectVersion=1.0

sonar.sources=glideit/
sonar.tests=tests/
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.version=3.11

sonar.sourceEncoding=UTF-8

sonar.python.xunit.reportPath=test-results.xml
